# Generated by Django 2.0.6 on 2018-10-21 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=255)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(choices=[('P', 'Pay'), ('R', 'Receive')], default='P', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.PaymentStatus'),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.PaymentType'),
        ),
        migrations.AddField(
            model_name='payments',
            name='users',
            field=models.ManyToManyField(through='payments.PaymentMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmembership',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.PaymentType'),
        ),
        migrations.AddField(
            model_name='paymentmembership',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Payments'),
        ),
        migrations.AddField(
            model_name='paymentmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
