# Generated by Django 2.0.6 on 2018-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
