# Generated by Django 2.0.6 on 2018-07-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payto_receivefrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='title',
            new_name='subject',
        ),
    ]
