# Generated by Django 2.0.6 on 2018-07-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20180729_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='details',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
