# Generated by Django 2.0.6 on 2018-10-20 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_auto_20180729_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payto',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='payto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receivefrom',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='receivefrom',
            name='user',
        ),
        migrations.AddField(
            model_name='payments',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payments',
            name='created_by',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='PayTo',
        ),
        migrations.DeleteModel(
            name='ReceiveFrom',
        ),
    ]
