# Generated by Django 2.0.6 on 2018-10-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembership',
            old_name='groups',
            new_name='group',
        ),
    ]
